//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int carID { get; set; }
        public string pickL { get; set; }
        public string pickD { get; set; }
        public string pickT { get; set; }
        public string dropL { get; set; }
        public string dropD { get; set; }
        public string dropT { get; set; }
        public string airportName { get; set; }
        public string carName { get; set; }
        public string picName { get; set; }
        public string passengers { get; set; }
        public string luggage { get; set; }
        public string doors { get; set; }
        public string category { get; set; }
        public string spec { get; set; }
        public string included { get; set; }
        public string price { get; set; }
        public string supplier { get; set; }
        public string daysRent { get; set; }
    }
}
