//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarService
    {
        public int CserviceID { get; set; }
        public string pickCity { get; set; }
        public string dropCity { get; set; }
        public Nullable<int> carID { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
