//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSearch
    {
        public int id { get; set; }
        public string pickUpL { get; set; }
        public string dropOffL { get; set; }
        public string pickUpD { get; set; }
        public string dropOffD { get; set; }
        public string pickUpT { get; set; }
        public string dropOffT { get; set; }
        public string airportName { get; set; }
        public string picName { get; set; }
        public string carName { get; set; }
        public string noPassengers { get; set; }
        public string luggage { get; set; }
        public string noDoors { get; set; }
        public string spec { get; set; }
        public string included { get; set; }
        public string priceDay { get; set; }
        public string totPrice { get; set; }
        public string category { get; set; }
        public string supplier { get; set; }
        public string daysRent { get; set; }
        public Nullable<int> carID { get; set; }
    }
}
