//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightService
    {
        public int FserviceID { get; set; }
        public string DeptCity { get; set; }
        public string ArrCity { get; set; }
        public string AirportName { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
