//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDetail
    {
        public int HotelId { get; set; }
        public string InDate { get; set; }
        public string OutDate { get; set; }
        public string Rooms { get; set; }
        public string Nights { get; set; }
        public string HotelPic { get; set; }
        public string RoomType { get; set; }
        public string Star { get; set; }
        public string Landmark { get; set; }
        public string Destination { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress { get; set; }
        public string Included { get; set; }
        public string Near { get; set; }
    }
}
