//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int bookID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string CardType { get; set; }
        public string SecurityCode { get; set; }
        public string Price { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string Date { get; set; }
        public string CardNumber { get; set; }
        public string PricePaid { get; set; }
        public string DatePaid { get; set; }
    }
}
