//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaceSearchEntities10 : DbContext
    {
        public PlaceSearchEntities10()
            : base("name=PlaceSearchEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SearchPlace> SearchPlaces { get; set; }

        public System.Data.Entity.DbSet<WebApi.Models.FlightDetail> FlightDetails { get; set; }
    }
}
